model:
  base_learning_rate: 2e-5
  target: taming.models.vqgan.VQModel
  params:
    num_classes: 4
    ckpt_path: /home/users/ntu/mohor001/BraSyn_2025_Task8/VQ-GAN/logs/2025-06-25T21-12-41_brats_vqgan_stage1/lightning_logs/2025-06-25T21-12-41_brats_vqgan_stage1/checkpoints/epoch=99-step=74600.ckpt
    ignore_keys: ["loss.discriminator.main.0.weight", "loss.discriminator.main.0.bias", "loss.discriminator.main.11.weight","loss.discriminator.main.11.bias"]
    stage: 2
    embed_dim: 4
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 4
      resolution: 192
      in_channels: 1
      out_ch: 1
      ch: 64
      num_groups: 32
      ch_mult:
      - 1
      - 1
      - 2
      num_res_blocks: 1
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 4
        disc_start: 0
        disc_weight: 0.8
        disc_factor: 0
        codebook_weight: 0
        num_classes: 5 # num_class + fake class

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 12
    train:
      target: taming.data.brats.BraTS2021Train
      params:
        data_path: [/scratch/users/ntu/mohor001/Task8DataBrats/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData, /scratch/users/ntu/mohor001/Task8DataBrats/ASNR-MICCAI-BraTS2023-MET-Challenge-TrainingData, /scratch/users/ntu/mohor001/Task8DataBrats/ASNR-MICCAI-BraTS2023-MET-Challenge-TrainingData_Additional] # to be filled
      phase: train
    validation:
      target: taming.data.brats.BraTS2021Test
      params:
        data_path: [/scratch/users/ntu/mohor001/Task8DataBrats/ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData, /scratch/users/ntu/mohor001/Task8DataBrats/ASNR-MICCAI-BraTS2023-MET-Challenge-ValidationData] # to be filled
      phase: val
    test:
      target: taming.data.brats.BraTS2021Test
      params:
        data_path: [/scratch/users/ntu/mohor001/Task8DataBrats/ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData, /scratch/users/ntu/mohor001/Task8DataBrats/ASNR-MICCAI-BraTS2023-MET-Challenge-ValidationData] # to be filled
      phase: test
